[package]
name = "syrillian"
description = "Real-time 3D game engine built on top of wgpu, focusing on flexibility, modularity, and a straightforward, entity-component-driven workflow"
license = "MIT"
repository = "https://github.com/Kek5chen/syrillian"
authors = [ "Kek5chen" ]
version = "0.1.2"
edition = "2024"



#################################################
#               Simple dependencies             #
#################################################



[dependencies]
winit = { version = "0.30.9", features = ["x11"] }
bytemuck = "1.23.0"
log = "0.4.22"
nalgebra = { version = "0.33.2" }
num-traits = "0.2.19"
itertools = "0.14.0"
image = "0.25.6"
rapier3d = "0.25.0"
futures = "0.3.31"
aligned = "0.4.2"
static_assertions = "1.1.0"

[build-dependencies]
chrono = "0.4.41"

[dev-dependencies]
chrono = "0.4.41"
env_logger = { version = "0.11.8", features = ["auto-color"] }



#################################################
#              Complex dependencies             #
#################################################



[dependencies.wgpu]
version = "25.0.0"
default-features = false
features = [
  "vulkan-portability",
  "wgpu-core",

  # Backends
  "vulkan",
  "metal",
  "dx12",
  "gles",

  # Shader compatibility
  "wgsl"
]

[dependencies.tokio]
version = "1.40.0"
features = ["rt", "rt-multi-thread", "macros", "sync"]

[dependencies.russimp-ng]
git = "https://github.com/Kek5chen/russimp-ng"
features = ["static-link"]



#################################################
#                Build Profiles                 #
#################################################



[profile.dev]
opt-level = 2

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"

