[package]
name = "syrillian"
description = "Real-time 3D game engine built on top of wgpu, focusing on flexibility, modularity, and a straightforward, entity-component-driven workflow"
license = "MIT"
repository = "https://github.com/Kek5chen/syrillian"
authors = [ "Kek5chen" ]
version = "0.1.2"
edition = "2024"

[dependencies]
wgpu = { version = "25.0.0", features = ["vulkan-portability"] }
tokio = { version = "1.40.0", features = ["rt", "rt-multi-thread", "macros"] }
winit = { version = "0.30.9", features = ["x11"] }
bytemuck = "1.18.0"
log = "0.4.22"
nalgebra = { version = "0.33.0" }
num-traits = "0.2.19"
russimp = "3.2.0"
itertools = "0.14.0"
image = "0.25.2"
rapier3d = "0.24.0"
futures = "0.3.30"

[build-dependencies]
chrono = "0.4.38"

[dev-dependencies]
chrono = "0.4.38"
env_logger = { version = "0.11.5", features = ["auto-color"] }

[profile.dev]
opt-level = 2
