name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        profile: [ debug, release ]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Ubuntu System Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y pkg-config libudev-dev libfontconfig-dev

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ matrix.os }}-${{ matrix.profile }}

      - name: Build and Test
        shell: bash
        run: |
          set -e
          FLAGS=""
          if [ "${{ matrix.profile }}" = "release" ]; then FLAGS="--release"; fi
          cargo build --workspace --locked $FLAGS --no-default-features --features derive
          cargo test  --workspace --locked $FLAGS --no-default-features --features derive