name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        run: rustup toolchain install stable --profile minimal --no-self-update

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2.7.8

      - name: Build
        run: cargo build --workspace --no-default-features --features derive

      - name: Build release
        run: cargo build --workspace --release --no-default-features --features derive